# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.164
neo_version_range=[21.1.164,)
loader_version_range=[1,)

mod_id=oc2
mod_name=OpenComputers II
mod_license=MIT
mod_group_id=li.cil.oc2
mod_authors=Sangar
mod_description=Modern computers for the modern player.\n\nThis mod uses the Terminus Font under the Open Font License. The full license can be found in the JAR of this mod.

semver=0.0.0

curse_project_id=437654
jei_version=19.21.2.313
jei_version_range=[19.21.2,)
jade_project_id=324717
jade_file_id=7545219
jade_version=15.10.5
jade_version_range=[15.10.5,)
markdown_manual_project_id=1412825
markdown_manual_file_id=7374817
sedna_project_id=511276
architectury_version=13.0.8
sedna_version_range=[1.0.14,)
markdown_manual_version_range=[1.0,)
