pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

rootProject.name = "oc2-1.21.1-neoforge"

def substituteLocal(final directoryName, final libraryName) {
    final def path = new File("../${directoryName}");
    if (path.exists()) {
        println("Found local [${directoryName}] project, substituting...")
        includeBuild(path) {
            dependencySubstitution {
                substitute module(libraryName) using project(':')
            }
        }
    }
}

substituteLocal('sedna-mc', 'curse.maven:sedna-511276')
substituteLocal('ceres', 'li.cil.ceres:ceres')
substituteLocal('sedna', 'li.cil.sedna:sedna')
substituteLocal('buildroot', 'li.cil.sedna:sedna-buildroot')
